branches:
  only:
  - master
  - gh-pages
language: node_js
node_js:
- '0.10'
before_install:
- npm install -g grunt-cli recess bower
- bower install
script: grunt swatch
git:
  depth: 10
deploy:
  provider: npm
  email: hello@thomaspark.co
  api_key:
    secure: E9dTc33u8aHCXG4qd8TrafOiAMzgEJYQUx/bnG2thb4cDD2U64LEdShjkXnjwr2K2RLNfQ4IQWHsDVAvyDK0f9kiud0swoG0SHTU9RDQ+NYFYODZe/c5qOlYqIHoJIpLV3lb7AHrzhrk+G1bkTn7pukB6/nEU0e+D3I7b3kbwEg=
  on:
    tags: true
    repo: thomaspark/bootswatch
    branch: gh-pages
